project:
  type: book

book:
  title: ""
  author: "Jon Sadler"
  date: "8/8/2025"
  chapters:
    - index.qmd
    - preface.qmd
    - chap1.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - chap6.qmd
    - chap7.qmd
    - chap8.qmd
    - chap9.qmd
    - chap10.qmd
 #  - references.qmd

bibliography: /Users/jonsadler/Documents/GitHub/Common Resources/My Library.bib

format:
  html:
     # --- THIS IS THE FIX ---
    # Set the Table of Contents depth to include level-3 headings (###)
    toc-depth: 3
    theme:
      - /Users/jonsadler/Documents/GitHub/Common Resources/custom-fonts.scss
  pdf:
    documentclass: scrreprt

editor: visual


